### ISSUE TITLE
FindCard / FindDeck should not filter individual keywords but filter the whole string

### ISSUE THREAD

**Issue by rockman007372** [AY2223S2-CS2103T-W11-3/tp#252]
`findCards what is a loop` should return only one card, instead of returning all the cards with keyword `what`. Does this make sense @ruiyigan ?

**Comment by ruiyigan** [comment]
Ok so switching from an `OR` search to an `AND` search? I'm not sure which is better actually.
I think the benefit of the current implementation is that it is more flexible. For example, if I want to only search for `How` and `What` questions I can just do findCards `how what` which can't be done if we implement the `AND` search.

I think I may prefer the `OR` search actually because I don't see someone typing `findCards what is a loop` as they probably just type `findCards loop`. But we can discuss with the rest too!
